import type { ComponentEntry } from "@/lib/registry/types";

/**
 * The shipped component taxonomy as typed entries. IDs, shapes, and STRIDE roles are copied
 * verbatim from the legacy `COMPONENT_LIBRARY`; `category`/`provider`/`keywords` are
 * presentation metadata (a wrong provider is a fixable label bug, not a schema break).
 * Declaration order is preserved so `listCategories()` and palette tab order are unchanged.
 *
 * The final three entries (`process`, `data_store`, `external_entity`) are the legacy DFD
 * types admitted by `#59` Step 9. They are `deprecated` (kept out of the palette) and their
 * `strideRole` matches the Rust engine (`src-tauri/src/stride/mod.rs`), closing the
 * desktop/browser threat divergence documented in `stride-role-parity.test.ts`.
 */
export const COMPONENT_ENTRIES: readonly ComponentEntry[] = [
	{
		id: "generic",
		label: "Generic",
		aliases: [],
		category: "generic",
		provider: "generic",
		iconId: "box",
		shape: "rounded",
		strideRole: "service",
		keywords: ["generic", "component", "node"],
		variants: [],
		status: "active",
	},
	{
		id: "text",
		label: "Text",
		aliases: [],
		category: "annotations",
		provider: "generic",
		iconId: "type",
		shape: "text",
		strideRole: "none",
		keywords: ["text", "label", "annotation", "note"],
		variants: [],
		status: "active",
	},
	{
		id: "web_server",
		label: "Web Server",
		aliases: [],
		category: "services",
		provider: "generic",
		iconId: "globe",
		shape: "rounded",
		strideRole: "service",
		keywords: ["web", "server", "http", "nginx", "apache", "iis"],
		variants: [],
		status: "active",
	},
	{
		id: "api_gateway",
		label: "API Gateway",
		aliases: [],
		category: "services",
		provider: "generic",
		iconId: "router",
		shape: "rounded",
		strideRole: "service",
		keywords: ["api", "gateway", "rest", "graphql", "kong", "apigee"],
		variants: [],
		status: "active",
	},
	{
		id: "microservice",
		label: "Microservice",
		aliases: [],
		category: "services",
		provider: "generic",
		iconId: "boxes",
		shape: "rounded",
		strideRole: "service",
		keywords: ["microservice", "service", "backend", "container"],
		variants: [],
		status: "active",
	},
	{
		id: "serverless_function",
		label: "Serverless Function",
		aliases: [],
		category: "services",
		provider: "generic",
		iconId: "zap",
		shape: "rounded",
		strideRole: "service",
		keywords: ["serverless", "lambda", "function", "cloud", "azure functions", "cloud functions"],
		variants: [],
		status: "active",
	},
	{
		id: "background_worker",
		label: "Background Worker",
		aliases: [],
		category: "services",
		provider: "generic",
		iconId: "cog",
		shape: "rounded",
		strideRole: "service",
		keywords: ["worker", "background", "job", "cron", "scheduler", "queue consumer"],
		variants: [],
		status: "active",
	},
	{
		id: "sql_database",
		label: "SQL Database",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "database",
		shape: "database",
		strideRole: "store",
		keywords: ["sql", "database", "postgres", "mysql", "sqlite", "mssql", "relational"],
		variants: [
			{
				id: "rds",
				label: "AWS RDS",
				aliases: [],
				provider: "aws",
				iconId: "database",
				status: "active",
			},
			{
				id: "azure_sql",
				label: "Azure SQL",
				aliases: [],
				provider: "azure",
				iconId: "database",
				status: "active",
			},
			{
				id: "cloud_sql",
				label: "Cloud SQL",
				aliases: [],
				provider: "gcp",
				iconId: "database",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "nosql_database",
		label: "NoSQL Database",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "hard-drive",
		shape: "database",
		strideRole: "store",
		keywords: ["nosql", "mongodb", "dynamodb", "cassandra", "couchdb", "document"],
		variants: [
			{
				id: "dynamodb",
				label: "DynamoDB",
				aliases: [],
				provider: "aws",
				iconId: "hard-drive",
				status: "active",
			},
			{
				id: "cosmosdb",
				label: "Cosmos DB",
				aliases: [],
				provider: "azure",
				iconId: "hard-drive",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "cache",
		label: "Cache",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "memory-stick",
		shape: "database",
		strideRole: "store",
		keywords: ["cache", "redis", "memcached", "in-memory", "session"],
		variants: [
			{
				id: "redis",
				label: "Redis",
				aliases: [],
				provider: "oss",
				iconId: "redis",
				status: "active",
			},
			{
				id: "memcached",
				label: "Memcached",
				aliases: [],
				provider: "oss",
				iconId: "memory-stick",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "search_index",
		label: "Search Index",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "search",
		shape: "database",
		strideRole: "store",
		keywords: ["search", "elasticsearch", "solr", "opensearch", "index", "full-text"],
		variants: [],
		status: "active",
	},
	{
		id: "object_storage",
		label: "Object Storage",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "archive",
		shape: "database",
		strideRole: "store",
		keywords: ["object", "storage", "s3", "blob", "gcs", "minio", "file"],
		variants: [
			{
				id: "s3",
				label: "AWS S3",
				aliases: [],
				provider: "aws",
				iconId: "archive",
				status: "active",
			},
			{
				id: "azure_blob",
				label: "Azure Blob",
				aliases: [],
				provider: "azure",
				iconId: "archive",
				status: "active",
			},
			{
				id: "gcs",
				label: "Google Cloud Storage",
				aliases: [],
				provider: "gcp",
				iconId: "archive",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "message_queue",
		label: "Message Queue",
		aliases: [],
		category: "messaging",
		provider: "generic",
		iconId: "mail-open",
		shape: "rounded",
		strideRole: "service",
		keywords: ["queue", "message", "rabbitmq", "sqs", "amqp", "async"],
		variants: [
			{
				id: "sqs",
				label: "AWS SQS",
				aliases: [],
				provider: "aws",
				iconId: "mail-open",
				status: "active",
			},
			{
				id: "rabbitmq",
				label: "RabbitMQ",
				aliases: [],
				provider: "oss",
				iconId: "mail-open",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "event_bus",
		label: "Event Bus",
		aliases: [],
		category: "messaging",
		provider: "generic",
		iconId: "radio",
		shape: "rounded",
		strideRole: "service",
		keywords: ["event", "bus", "kafka", "sns", "pubsub", "eventbridge"],
		variants: [
			{
				id: "kafka",
				label: "Kafka",
				aliases: [],
				provider: "oss",
				iconId: "kafka",
				status: "active",
			},
			{
				id: "sns",
				label: "AWS SNS",
				aliases: [],
				provider: "aws",
				iconId: "radio",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "stream_processor",
		label: "Stream Processor",
		aliases: [],
		category: "messaging",
		provider: "generic",
		iconId: "activity",
		shape: "rounded",
		strideRole: "service",
		keywords: ["stream", "processor", "kinesis", "flink", "spark", "realtime"],
		variants: [],
		status: "active",
	},
	{
		id: "load_balancer",
		label: "Load Balancer",
		aliases: [],
		category: "infrastructure",
		provider: "generic",
		iconId: "scale",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["load", "balancer", "lb", "alb", "nlb", "haproxy", "traffic"],
		variants: [],
		status: "active",
	},
	{
		id: "cdn",
		label: "CDN",
		aliases: [],
		category: "infrastructure",
		provider: "generic",
		iconId: "globe",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["cdn", "cloudfront", "cloudflare", "akamai", "content", "delivery"],
		variants: [
			{
				id: "cloudfront",
				label: "CloudFront",
				aliases: [],
				provider: "aws",
				iconId: "globe",
				status: "active",
			},
			{
				id: "cloudflare",
				label: "Cloudflare",
				aliases: [],
				provider: "cloudflare",
				iconId: "globe",
				status: "active",
			},
		],
		status: "active",
	},
	{
		id: "dns",
		label: "DNS",
		aliases: [],
		category: "infrastructure",
		provider: "generic",
		iconId: "at-sign",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["dns", "domain", "route53", "nameserver", "resolution"],
		variants: [],
		status: "active",
	},
	{
		id: "proxy",
		label: "Proxy",
		aliases: [],
		category: "infrastructure",
		provider: "generic",
		iconId: "arrow-left-right",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["proxy", "reverse", "forward", "envoy", "traefik", "haproxy"],
		variants: [],
		status: "active",
	},
	{
		id: "container",
		label: "Container",
		aliases: [],
		category: "infrastructure",
		provider: "generic",
		iconId: "container",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["container", "docker", "kubernetes", "k8s", "pod", "orchestration"],
		variants: [],
		status: "active",
	},
	{
		id: "auth_provider",
		label: "Auth Provider",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "key-round",
		shape: "rounded",
		strideRole: "service",
		keywords: ["auth", "oauth", "oidc", "saml", "identity", "idp", "okta", "auth0"],
		variants: [],
		status: "active",
	},
	{
		id: "firewall",
		label: "Firewall",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "shield-check",
		shape: "rounded",
		strideRole: "service",
		keywords: ["firewall", "waf", "security", "filter", "network", "acl"],
		variants: [],
		status: "active",
	},
	{
		id: "secret_manager",
		label: "Secret Manager",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "lock",
		shape: "database",
		strideRole: "store",
		keywords: ["secret", "vault", "hashicorp", "aws secrets", "key management", "kms"],
		variants: [],
		status: "active",
	},
	{
		id: "certificate_authority",
		label: "Certificate Authority",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "file-badge",
		shape: "rounded",
		strideRole: "service",
		keywords: ["certificate", "ca", "tls", "ssl", "pki", "x509"],
		variants: [],
		status: "active",
	},
	{
		id: "web_browser",
		label: "Web Browser",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "monitor-smartphone",
		shape: "rect",
		strideRole: "actor",
		keywords: ["browser", "web", "client", "frontend", "spa", "pwa"],
		variants: [],
		status: "active",
	},
	{
		id: "mobile_app",
		label: "Mobile App",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "smartphone",
		shape: "rect",
		strideRole: "actor",
		keywords: ["mobile", "app", "ios", "android", "react native", "flutter"],
		variants: [],
		status: "active",
	},
	{
		id: "desktop_app",
		label: "Desktop App",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "monitor",
		shape: "rect",
		strideRole: "actor",
		keywords: ["desktop", "app", "electron", "tauri", "native", "windows", "macos"],
		variants: [],
		status: "active",
	},
	{
		id: "iot_device",
		label: "IoT Device",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "cpu",
		shape: "rect",
		strideRole: "actor",
		keywords: ["iot", "device", "sensor", "embedded", "hardware", "edge"],
		variants: [],
		status: "active",
	},
	{
		id: "api_client",
		label: "API Client",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "code-2",
		shape: "rect",
		strideRole: "actor",
		keywords: ["api", "client", "sdk", "library", "integration", "consumer"],
		variants: [],
		status: "active",
	},
	{
		id: "cli_tool",
		label: "CLI Tool",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "terminal",
		shape: "rect",
		strideRole: "actor",
		keywords: ["cli", "command", "terminal", "shell", "script", "automation"],
		variants: [],
		status: "active",
	},
	{
		id: "vpn_gateway",
		label: "VPN Gateway",
		aliases: [],
		category: "networking",
		provider: "generic",
		iconId: "shield",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["vpn", "gateway", "tunnel", "ipsec", "wireguard", "openvpn", "private"],
		variants: [],
		status: "active",
	},
	{
		id: "api_endpoint",
		label: "API Endpoint",
		aliases: [],
		category: "networking",
		provider: "generic",
		iconId: "waypoints",
		shape: "rounded",
		strideRole: "service",
		keywords: ["api", "endpoint", "rest", "graphql", "route", "url"],
		variants: [],
		status: "active",
	},
	{
		id: "webhook",
		label: "Webhook",
		aliases: [],
		category: "networking",
		provider: "generic",
		iconId: "webhook",
		shape: "rounded",
		strideRole: "service",
		keywords: ["webhook", "callback", "hook", "notification", "event", "http"],
		variants: [],
		status: "active",
	},
	{
		id: "service_mesh",
		label: "Service Mesh",
		aliases: [],
		category: "networking",
		provider: "generic",
		iconId: "network",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["mesh", "istio", "linkerd", "envoy", "sidecar", "service mesh"],
		variants: [],
		status: "active",
	},
	{
		id: "file_storage",
		label: "File Storage",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "folder-archive",
		shape: "database",
		strideRole: "store",
		keywords: ["file", "storage", "nas", "nfs", "efs", "shared", "filesystem"],
		variants: [],
		status: "active",
	},
	{
		id: "data_lake",
		label: "Data Lake",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "waves",
		shape: "database",
		strideRole: "store",
		keywords: ["data", "lake", "warehouse", "bigquery", "redshift", "snowflake", "analytics"],
		variants: [],
		status: "active",
	},
	{
		id: "backup_service",
		label: "Backup Service",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "cloud-upload",
		shape: "database",
		strideRole: "store",
		keywords: ["backup", "recovery", "disaster", "snapshot", "archive", "retention"],
		variants: [],
		status: "active",
	},
	{
		id: "waf",
		label: "WAF",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "shield-alert",
		shape: "rounded",
		strideRole: "service",
		keywords: ["waf", "web", "application", "firewall", "owasp", "rules", "modsecurity"],
		variants: [],
		status: "active",
	},
	{
		id: "siem",
		label: "SIEM",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "radar",
		shape: "rounded",
		strideRole: "service",
		keywords: ["siem", "log", "aggregator", "splunk", "sentinel", "elk", "monitoring", "detection"],
		variants: [],
		status: "active",
	},
	{
		id: "identity_provider",
		label: "Identity Provider",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "user-check",
		shape: "rounded",
		strideRole: "service",
		keywords: ["identity", "idp", "sso", "saml", "oidc", "active directory", "entra"],
		variants: [],
		status: "active",
	},
	{
		id: "key_management",
		label: "Key Management",
		aliases: [],
		category: "security",
		provider: "generic",
		iconId: "key-square",
		shape: "database",
		strideRole: "store",
		keywords: ["kms", "key", "management", "encryption", "hsm", "aws kms", "azure key vault"],
		variants: [],
		status: "active",
	},
	{
		id: "kubernetes",
		label: "Kubernetes",
		aliases: [],
		category: "platform",
		provider: "generic",
		iconId: "ship",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["kubernetes", "k8s", "cluster", "orchestration", "aks", "eks", "gke"],
		variants: [],
		status: "active",
	},
	{
		id: "serverless_platform",
		label: "Serverless Platform",
		aliases: [],
		category: "platform",
		provider: "generic",
		iconId: "cloud-cog",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["serverless", "platform", "faas", "cloud run", "app runner", "cloud functions"],
		variants: [],
		status: "active",
	},
	{
		id: "ci_cd_pipeline",
		label: "CI/CD Pipeline",
		aliases: [],
		category: "platform",
		provider: "generic",
		iconId: "git-branch",
		shape: "hexagon",
		strideRole: "service",
		keywords: ["ci", "cd", "pipeline", "github actions", "jenkins", "gitlab", "build", "deploy"],
		variants: [],
		status: "active",
	},
	{
		id: "container_registry",
		label: "Container Registry",
		aliases: [],
		category: "platform",
		provider: "generic",
		iconId: "package-check",
		shape: "database",
		strideRole: "store",
		keywords: ["container", "registry", "docker", "ecr", "acr", "gcr", "harbor", "image"],
		variants: [],
		status: "active",
	},
	// ── Legacy DFD types (#59 Step 9): deprecated, out of palette, Rust-parity STRIDE ──
	{
		id: "process",
		label: "Process",
		aliases: [],
		category: "services",
		provider: "generic",
		iconId: "box",
		shape: "rounded",
		strideRole: "service",
		keywords: ["process", "dfd", "legacy"],
		variants: [],
		status: "deprecated",
	},
	{
		id: "data_store",
		label: "Data Store",
		aliases: [],
		category: "databases",
		provider: "generic",
		iconId: "database",
		shape: "database",
		strideRole: "store",
		keywords: ["data", "store", "dfd", "legacy"],
		variants: [],
		status: "deprecated",
	},
	{
		id: "external_entity",
		label: "External Entity",
		aliases: [],
		category: "clients",
		provider: "generic",
		iconId: "box",
		shape: "rect",
		strideRole: "actor",
		keywords: ["external", "entity", "actor", "dfd", "legacy"],
		variants: [],
		status: "deprecated",
	},
];
