/** Rotating tips and security wisdom for the welcome screen. */
export const TIPS: string[] = [
	"Threat modeling is most effective when done early in the design phase.",
	"STRIDE: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege.",
	"The best threat model is one that gets maintained over time.",
	"Every data flow that crosses a trust boundary deserves scrutiny.",
	"Think like an attacker, defend like an architect.",
	"A threat model is a living document — update it as your system evolves.",
	"External entities are outside your control. That's what makes them interesting.",
	"Trust boundaries are where the security story gets compelling.",
	"Processes are where data transforms — and where bugs hide.",
	"Data stores are high-value targets. Encrypt at rest, restrict access.",
	"Authentication is easy to get wrong and hard to get right.",
	"The simplest architecture is often the most secure architecture.",
	"Git-tracked threat models enable security code review.",
	"AI can suggest threats you haven't considered — but you decide what matters.",
	"A mitigation without verification is just a hope.",
	"Security is a process, not a product. — Bruce Schneier",
	"The only truly secure system is one that is powered off. — Gene Spafford",
	"Complexity is the enemy of security. — Bruce Schneier",
	"Threat modeling finds design-level flaws that testing cannot.",
	"Defense in depth: no single control should be the only thing standing between an attacker and your data.",
	"Every assumption in your architecture is a potential threat.",
	"Denial of service isn't always about bandwidth — sometimes it's about logic.",
	"Repudiation threats are easy to overlook and hard to fix after the fact.",
	"The best time to threat model was yesterday. The second best time is now.",
	"Good security starts with knowing what you're protecting and why.",
];
