name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the pain point?
      placeholder: "I need to import threat models from Microsoft TMT, but there's no way to do that currently."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work? Be as specific as you can.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider? Why is your proposal better?

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Important -- affects my workflow
        - Critical -- blocking my use of ThreatForge

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, examples from other tools, links to relevant standards, etc.
