// @vitest-environment node
//
// This is a Node script, not a DOM module. Pinning the environment keeps the
// scripts lane independent of the app's jsdom setup.
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { renderSummary, summarizeReport } from "./summarize-playwright.mjs";

const scriptPath = join(import.meta.dirname, "summarize-playwright.mjs");

// Fixtures mirror @playwright/test 1.61.1's `JSONReport` (node_modules/playwright/types/
// testReporter.d.ts), cross-checked against a real report generated by running a throwaway
// suite containing a passing, flaky, failing, timing-out, and skipped test. Only the fields
// the summarizer reads are populated. `tests[]` holds one entry per Playwright project; this
// repository configures a single `chromium` project, so each spec carries exactly one.

/**
 * @param {string} title
 * @param {string} file
 * @param {number} line
 * @param {"expected" | "unexpected" | "flaky" | "skipped"} status
 * @param {string[]} attempts One `results[].status` per attempt, oldest first.
 */
const spec = (title, file, line, status, attempts) => ({
	title,
	file,
	line,
	ok: status === "expected" || status === "flaky" || status === "skipped",
	tests: [{ status, results: attempts.map((attemptStatus) => ({ status: attemptStatus })) }],
});

/**
 * @param {number} duration
 * @param {unknown[]} suites
 */
const report = (duration, suites, errors = []) => ({
	config: { rootDir: "/repo/e2e" },
	suites,
	errors,
	stats: { startTime: "2026-07-21T10:00:00.000Z", duration },
});

const allPassReport = report(83_000, [
	{
		title: "canvas-elements.spec.ts",
		file: "canvas-elements.spec.ts",
		specs: [
			spec("adds a process node", "canvas-elements.spec.ts", 12, "expected", ["passed"]),
			spec("deletes a node", "canvas-elements.spec.ts", 24, "expected", ["passed"]),
		],
		suites: [
			{
				title: "Visual regression",
				file: "canvas-visual.spec.ts",
				specs: [
					spec("matches the canvas baseline", "canvas-visual.spec.ts", 45, "skipped", ["skipped"]),
					spec("matches the palette baseline", "canvas-visual.spec.ts", 60, "skipped", ["skipped"]),
				],
			},
		],
	},
]);

const oneFlakyReport = report(12_300, [
	{
		title: "canvas-elements.spec.ts",
		file: "canvas-elements.spec.ts",
		specs: [spec("deletes a node", "canvas-elements.spec.ts", 24, "expected", ["passed"])],
		suites: [
			{
				title: "Canvas Elements",
				file: "canvas-elements.spec.ts",
				specs: [
					spec("adds a process node", "canvas-elements.spec.ts", 12, "flaky", ["failed", "passed"]),
				],
			},
		],
	},
]);

const oneFailedReport = report(30_500, [
	{
		title: "dirty-state.spec.ts",
		file: "dirty-state.spec.ts",
		specs: [spec("marks the model dirty", "dirty-state.spec.ts", 12, "expected", ["passed"])],
		suites: [
			{
				title: "Dirty State",
				file: "dirty-state.spec.ts",
				specs: [
					spec("warns before closing", "dirty-state.spec.ts", 30, "unexpected", [
						"failed",
						"failed",
						"failed",
					]),
				],
			},
		],
	},
]);

const mixedReport = report(7385.539, [
	{
		title: "mixed.spec.ts",
		file: "mixed.spec.ts",
		specs: [
			spec("skipped on purpose", "mixed.spec.ts", 19, "skipped", ["skipped"]),
			spec("times out", "mixed.spec.ts", 23, "unexpected", ["timedOut", "timedOut", "timedOut"]),
		],
		suites: [
			{
				title: "Outer group",
				file: "mixed.spec.ts",
				specs: [
					spec("fails every attempt", "mixed.spec.ts", 14, "unexpected", [
						"failed",
						"failed",
						"failed",
					]),
				],
				suites: [
					{
						title: "Inner group",
						file: "mixed.spec.ts",
						specs: [
							spec("passes cleanly", "mixed.spec.ts", 5, "expected", ["passed"]),
							spec("passes only after one retry", "mixed.spec.ts", 9, "flaky", [
								"failed",
								"passed",
							]),
						],
					},
				],
			},
		],
	},
]);

const render = (value) => renderSummary(summarizeReport(value));

describe("summarizeReport", () => {
	it("counts a skipped spec separately from a passing one", () => {
		expect(summarizeReport(allPassReport)).toMatchObject({
			passed: 2,
			failed: 0,
			timedOut: 0,
			flaky: 0,
			skipped: 2,
			durationMs: 83_000,
		});
	});

	it("classifies a retried pass as flaky and records its retry count", () => {
		const summary = summarizeReport(oneFlakyReport);

		expect(summary.flaky).toBe(1);
		expect(summary.passed).toBe(1);
		expect(summary.failedTests).toEqual([]);
		expect(summary.flakyTests).toEqual([
			{
				status: "flaky",
				title: "Canvas Elements > adds a process node",
				location: "canvas-elements.spec.ts:12",
				retries: 1,
				timedOut: false,
			},
		]);
	});

	it("separates a timed-out test from an assertion failure", () => {
		const summary = summarizeReport(mixedReport);

		expect(summary).toMatchObject({ passed: 1, failed: 1, timedOut: 1, flaky: 1, skipped: 1 });
		expect(summary.failedTests.map((outcome) => [outcome.title, outcome.timedOut])).toEqual([
			["times out", true],
			["Outer group > fails every attempt", false],
		]);
	});

	it("returns empty counts instead of throwing on a report of the wrong shape", () => {
		expect(summarizeReport(null)).toMatchObject({ passed: 0, skipped: 0, durationMs: null });
		expect(summarizeReport({ suites: "not-an-array" })).toMatchObject({ passed: 0 });
		expect(summarizeReport({ suites: [{ specs: [{ tests: [{}] }] }] })).toMatchObject({
			passed: 0,
			failed: 0,
		});
	});

	it("counts run-level errors that killed the run before any test reported", () => {
		// A webServer that never starts, or a spec that fails to import, produces
		// exactly this shape: zero suites and a non-empty errors array.
		const died = report(
			1200,
			[],
			[{ message: "Process from config.webServer was not able to start. Exit code: 3" }],
		);
		expect(summarizeReport(died)).toMatchObject({ passed: 0, failed: 0, runErrors: 1 });
	});

	it("counts an unknown status so the buckets stay additive", () => {
		const widened = report(500, [
			{
				title: "future.spec.ts",
				file: "future.spec.ts",
				specs: [spec("uses a future status", "future.spec.ts", 3, "quarantined", ["passed"])],
			},
		]);
		expect(summarizeReport(widened)).toMatchObject({ passed: 0, other: 1 });
	});
});

describe("renderSummary", () => {
	it("names run-level errors instead of claiming no tests were reported", () => {
		const died = report(
			1200,
			[],
			[
				{ message: "Process from config.webServer was not able to start. Exit code: 3" },
				{ message: "Error: Cannot find module './missing'" },
			],
		);
		const rendered = render(died);
		// The old wording read as "nothing happened, nothing to see" on a red job.
		expect(rendered).not.toContain("No tests were reported.");
		expect(rendered).toContain("No tests ran.");
		expect(rendered).toContain("2 run-level errors before any test could report");
	});

	it("uses the singular for one run-level error", () => {
		const died = report(900, [], [{ message: "boom" }]);
		expect(render(died)).toContain("1 run-level error before any test could report");
	});

	it("renders a single counts line when nothing needs attention", () => {
		expect(render(allPassReport)).toBe(
			["## Playwright E2E", "", "2 passed, 2 skipped in 1m 23s.", ""].join("\n"),
		);
	});

	it("names the flaky test, its file, and its retry count", () => {
		expect(render(oneFlakyReport)).toBe(
			[
				"## Playwright E2E",
				"",
				"1 passed, 1 flaky in 12.3s.",
				"",
				"### Flaky (passed after retry)",
				"",
				"| Test | Location | Retries |",
				"| --- | --- | --- |",
				"| Canvas Elements > adds a process node | `canvas-elements.spec.ts:12` | 1 |",
				"",
			].join("\n"),
		);
	});

	it("names the failed test with its outcome and retry count", () => {
		expect(render(oneFailedReport)).toBe(
			[
				"## Playwright E2E",
				"",
				"1 passed, 1 failed in 30.5s.",
				"",
				"### Failed",
				"",
				"| Test | Location | Outcome | Retries |",
				"| --- | --- | --- | --- |",
				"| Dirty State > warns before closing | `dirty-state.spec.ts:30` | failed | 2 |",
				"",
			].join("\n"),
		);
	});

	it("reports every outcome class in one summary", () => {
		expect(render(mixedReport)).toBe(
			[
				"## Playwright E2E",
				"",
				"1 passed, 1 failed, 1 timed out, 1 flaky, 1 skipped in 7.4s.",
				"",
				"### Flaky (passed after retry)",
				"",
				"| Test | Location | Retries |",
				"| --- | --- | --- |",
				"| Outer group > Inner group > passes only after one retry | `mixed.spec.ts:9` | 1 |",
				"",
				"### Failed",
				"",
				"| Test | Location | Outcome | Retries |",
				"| --- | --- | --- | --- |",
				"| times out | `mixed.spec.ts:23` | timed out | 2 |",
				"| Outer group > fails every attempt | `mixed.spec.ts:14` | failed | 2 |",
				"",
			].join("\n"),
		);
	});

	it("escapes a pipe in a test title so the table survives", () => {
		const piped = report(1200, [
			{
				title: "shortcuts.spec.ts",
				file: "shortcuts.spec.ts",
				specs: [
					spec("undo | redo round-trips", "shortcuts.spec.ts", 7, "flaky", ["failed", "passed"]),
				],
			},
		]);

		expect(render(piped)).toContain("| undo \\| redo round-trips | `shortcuts.spec.ts:7` | 1 |");
	});

	it("omits the duration when the report carries no stats", () => {
		const statsless = {
			suites: [
				{
					title: "canvas-elements.spec.ts",
					file: "canvas-elements.spec.ts",
					specs: [
						spec("adds a process node", "canvas-elements.spec.ts", 12, "expected", ["passed"]),
					],
				},
			],
		};

		expect(render(statsless)).toBe(["## Playwright E2E", "", "1 passed.", ""].join("\n"));
	});

	it("says so when the report contains no tests at all", () => {
		expect(render({ suites: [] })).toBe(
			["## Playwright E2E", "", "No tests were reported.", ""].join("\n"),
		);
	});
});

describe("summarize-playwright CLI", () => {
	let workDir = "";

	/**
	 * Runs the script and asserts it stayed advisory: it must always exit 0. Both
	 * GitHub Actions file-command variables default to unset so a test that does not
	 * pass one stays isolated from the real files this repo's own CI step exports —
	 * without this, an inherited `GITHUB_OUTPUT` would let the script append into the
	 * live step's output file instead of the test's throwaway one.
	 */
	const run = (args, env) => {
		const result = spawnSync(process.execPath, [scriptPath, ...args], {
			encoding: "utf8",
			env: { ...process.env, GITHUB_STEP_SUMMARY: "", GITHUB_OUTPUT: "", ...env },
		});

		expect(result.stderr).toBe("");
		expect(result.status).toBe(0);
		return result.stdout;
	};

	beforeAll(() => {
		workDir = mkdtempSync(join(tmpdir(), "summarize-playwright-"));
		writeFileSync(join(workDir, "results.json"), JSON.stringify(oneFlakyReport));
		writeFileSync(join(workDir, "all-pass.json"), JSON.stringify(allPassReport));
		writeFileSync(join(workDir, "malformed.json"), "{ not json");
	});

	afterAll(() => {
		rmSync(workDir, { recursive: true, force: true });
	});

	it("writes nothing when GITHUB_STEP_SUMMARY is unset", () => {
		expect(run([join(workDir, "results.json")])).toBe("");
	});

	it("prints the summary to stdout when asked for it locally", () => {
		expect(run([join(workDir, "results.json"), "--stdout"])).toContain(
			"| Canvas Elements > adds a process node | `canvas-elements.spec.ts:12` | 1 |",
		);
	});

	it("appends the summary to the GitHub step summary file", () => {
		const summaryFile = join(workDir, "step-summary.md");
		writeFileSync(summaryFile, "## Existing section\n");

		run([join(workDir, "results.json")], { GITHUB_STEP_SUMMARY: summaryFile });

		const written = readFileSync(summaryFile, "utf8");
		expect(written).toContain("## Existing section\n");
		expect(written).toContain("1 passed, 1 flaky in 12.3s.");
	});

	it("succeeds and reports the absence when the report file is missing", () => {
		const summaryFile = join(workDir, "missing-report-summary.md");

		run([join(workDir, "absent.json")], { GITHUB_STEP_SUMMARY: summaryFile });

		expect(readFileSync(summaryFile, "utf8")).toContain("No usable JSON report at");
	});

	it("succeeds and reports the failure when the report is malformed", () => {
		const summaryFile = join(workDir, "malformed-report-summary.md");

		run([join(workDir, "malformed.json")], { GITHUB_STEP_SUMMARY: summaryFile });

		expect(readFileSync(summaryFile, "utf8")).toContain("No usable JSON report at");
	});

	it("writes has-flaky=true to the GitHub output file when the report has a flaky test", () => {
		const outputFile = join(workDir, "flaky-output.txt");

		run([join(workDir, "results.json")], { GITHUB_OUTPUT: outputFile });

		// Exact GitHub Actions `key=value` file-command format: the workflow reads this
		// same output the summary is derived from, so it never re-parses the report.
		expect(readFileSync(outputFile, "utf8")).toBe("has-flaky=true\n");
	});

	it("writes has-flaky=false to the GitHub output file for a fully passing run", () => {
		const outputFile = join(workDir, "clean-output.txt");

		run([join(workDir, "all-pass.json")], { GITHUB_OUTPUT: outputFile });

		expect(readFileSync(outputFile, "utf8")).toBe("has-flaky=false\n");
	});

	it("writes has-flaky=false when the report can't be read, deferring to the job's own failure() check", () => {
		const outputFile = join(workDir, "missing-report-output.txt");

		run([join(workDir, "absent.json")], { GITHUB_OUTPUT: outputFile });

		expect(readFileSync(outputFile, "utf8")).toBe("has-flaky=false\n");
	});

	it("appends the output alongside an existing GitHub output file", () => {
		const outputFile = join(workDir, "existing-output.txt");
		writeFileSync(outputFile, "other-step-output=already-here\n");

		run([join(workDir, "results.json")], { GITHUB_OUTPUT: outputFile });

		const written = readFileSync(outputFile, "utf8");
		expect(written).toContain("other-step-output=already-here\n");
		expect(written).toContain("has-flaky=true\n");
	});

	it("fails closed when the GitHub output cannot be written", () => {
		const result = spawnSync(process.execPath, [scriptPath, join(workDir, "results.json")], {
			encoding: "utf8",
			// A directory cannot receive the file-command append. The non-zero step result makes the
			// workflow's `failure()` condition upload the diagnostics instead of losing flaky evidence.
			env: { ...process.env, GITHUB_STEP_SUMMARY: "", GITHUB_OUTPUT: workDir },
		});

		expect(result.status).not.toBe(0);
	});
});
